export { default as SplashScreen } from './SplashScreen'
export { default as SingIn } from './SingIn'
export { default as SingUp } from './SingUp'
export { default as ForgotPass } from './ForgotPass'
export { default as Dashboard } from './Dashboard'
