name: Android Build
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://fundmymusic-backend.herokuapp.com/api/concerts'
        method: 'GET'
        
